scan_timeout=10
command_timeout=100
add_newline=false

format= "$status[\\[](bold green) $battery$hostname$directory$git_branch$git_status$git_state[\\]](bold green)$jobs"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸"
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold yellow"

[python]
format = '[${symbol}${pyenv_prefix}(\($virtualenv\) )]($style)'

[status]
disabled=false
format="[$symbol]($style) "
map_symbol=true

[jobs]
symbol="âœ¦ "
